# Generated by Django 5.2 on 2025-05-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
