# Generated by Django 6.0.3 on 2026-03-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_fix_slug_maxlength'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True, help_text='Full project description shown on the detail page. Markdown supported.'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repo URL', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, help_text='One or two sentences shown on the project card. Plain text.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Paste a full iframe/embed snippet here (YouTube, GitHub Gist, Figma, etc.). Used on the detail page instead of the image if both are provided.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show on the home/projects grid'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a preview image. Appears on the card and at the top of the detail page.', null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='Live demo or external link', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma-separated: Python, React, PostgreSQL', max_length=300),
        ),
    ]
