# Generated by Django 6.0.3 on 2026-03-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Must match the block's mediaUrl value exactly (e.g. 'headshot', 'about-photo-1'). Check the Studio editor to find it.", unique=True)),
                ('label', models.CharField(help_text="Friendly name shown in admin (e.g. 'Home Page Headshot').", max_length=100)),
                ('image', models.ImageField(help_text='Upload the image. Replaces the old static file on all pages using this key.', upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Image',
                'verbose_name_plural': 'Site Images',
                'ordering': ['key'],
            },
        ),
        migrations.DeleteModel(
            name='SiteProfile',
        ),
    ]
