# Generated by Django 5.2 on 2025-05-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
